let today = new Date
let year = today.getFullYear()
let month = ('0' + (today.getMonth() + 1)).slice(-2);
let day = ('0' + today.getDate()).slice(-2);
let dateString = `${year}-${month}-${day}`

// Assignment 확인을 위해 서버를 실행하는 날짜로 발신 데이터의 광고 표시일을 설정합니다.

// 하루 송출할 데이터로 만들었습니다.

module.exports = {
    ads: [
        {
            id: 'AD_001',
            category: ['ELECTRONIC'],
            transmissionDate: dateString,
            startTime: '00:00',
            endTime: '04:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_002',
            category: ['ELECTRONIC'],
            transmissionDate: dateString,
            startTime: '00:00',
            endTime: '04:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_003',
            category: ['ELECTRONIC'],
            transmissionDate: dateString,
            startTime: '00:00',
            endTime: '04:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_004',
            category: ['ELECTRONIC'],
            transmissionDate: dateString,
            startTime: '00:00',
            endTime: '04:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_005',
            category: ['ELECTRONIC'],
            transmissionDate: dateString,
            startTime: '00:00',
            endTime: '04:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_006',
            category: ['CARE'],
            transmissionDate: dateString,
            startTime: '04:00',
            endTime: '08:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_007',
            category: ['CARE'],
            transmissionDate: dateString,
            startTime: '04:00',
            endTime: '08:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_008',
            category: ['CARE'],
            transmissionDate: dateString,
            startTime: '04:00',
            endTime: '08:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_009',
            category: ['CARE'],
            transmissionDate: dateString,
            startTime: '04:00',
            endTime: '08:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_010',
            category: ['CARE'],
            transmissionDate: dateString,
            startTime: '04:00',
            endTime: '08:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_011',
            category: ['RENTAL'],
            transmissionDate: dateString,
            startTime: '08:00',
            endTime: '12:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_012',
            category: ['RENTAL'],
            transmissionDate: dateString,
            startTime: '08:00',
            endTime: '12:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_013',
            category: ['RENTAL'],
            transmissionDate: dateString,
            startTime: '08:00',
            endTime: '12:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_014',
            category: ['RENTAL'],
            transmissionDate: dateString,
            startTime: '08:00',
            endTime: '12:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_015',
            category: ['RENTAL'],
            transmissionDate: dateString,
            startTime: '08:00',
            endTime: '12:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_016',
            category: ['TOUR'],
            transmissionDate: dateString,
            startTime: '12:00',
            endTime: '16:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_017',
            category: ['TOUR'],
            transmissionDate: dateString,
            startTime: '12:00',
            endTime: '16:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_018',
            category: ['TOUR'],
            transmissionDate: dateString,
            startTime: '12:00',
            endTime: '16:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_019',
            category: ['TOUR'],
            transmissionDate: dateString,
            startTime: '12:00',
            endTime: '16:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_020',
            category: ['TOUR'],
            transmissionDate: dateString,
            startTime: '12:00',
            endTime: '16:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_021',
            category: ['GROCERY', 'DELIVERY'],
            transmissionDate: dateString,
            startTime: '16:00',
            endTime: '20:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_022',
            category: ['GROCERY', 'DELIVERY'],
            transmissionDate: dateString,
            startTime: '16:00',
            endTime: '20:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_023',
            category: ['GROCERY', 'DELIVERY'],
            transmissionDate: dateString,
            startTime: '16:00',
            endTime: '20:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_024',
            category: ['GROCERY', 'DELIVERY'],
            transmissionDate: dateString,
            startTime: '16:00',
            endTime: '20:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_025',
            category: ['GROCERY', 'DELIVERY'],
            transmissionDate: dateString,
            startTime: '16:00',
            endTime: '20:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_026',
            category: ['MUSIC'],
            transmissionDate: dateString,
            startTime: '20:00',
            endTime: '24:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_027',
            category: ['MUSIC'],
            transmissionDate: dateString,
            startTime: '20:00',
            endTime: '24:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_028',
            category: ['MUSIC'],
            transmissionDate: dateString,
            startTime: '20:00',
            endTime: '24:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_029',
            category: ['MUSIC'],
            transmissionDate: dateString,
            startTime: '20:00',
            endTime: '24:00',
            limitPerDay: '96',
        },
        {
            id: 'AD_030',
            category: ['MUSIC'],
            transmissionDate: dateString,
            startTime: '20:00',
            endTime: '24:00',
            limitPerDay: '96',
        },
    ],
};
