

module.exports = {
    ads: [
        {
            id: 'AD_001',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_002',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_003',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_004',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_005',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_006',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_007',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_008',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_009',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
        {
            id: 'AD_010',
            category: 'DELIVERY',
            transmissionDate: '2022-10-15',
            startTime: '12:00',
            endTime: '18:00',
            limitPerDay: '10',
        },
    ],
};
